### ISSUE TITLE
Ability to filter by status code

### ISSUE THREAD

**Issue by imranismail** [imranismail/bff#1]
A status filter may prove useful in cases where you want to apply modifiers only when status match a specific code

```yaml
bff.URLFilter:
  path: /api/users
  modifier:
    bff.StatusFilter:
      statusCodes: [200, 201]
      modifier:
        body.JSONMapPatch:
          skipMissingPathOnRemove: true
          patch:
            - { op: move, from: /name, path: /Name }
            - { op: remove, path: /name }
```
